In [1]:
import pandas as pd
import numpy as np

In [2]:
#Set PANDAS to show all columns in DataFrame
pd.set_option('display.max_columns', None)

In [3]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [4]:
df = pd.read_csv('11Input/02DataProcessed/distanced.csv')
df.head()

,town,address,land_area,urb_zoning,nurb_zoning,nurb_land,date,object_num,story,material,completion_date,building_area,n_bed,n_hall,n_bath,d_comp,d_manager,price,unitprice,note,serialnumber,main_area,aux_area,balcony_area,d_elevator,trans_num,year,month,place_id,dist_to四城,dist_to宜蘭,dist_to縣政中心,dist_to羅東,dur_to四城,dur_to宜蘭,dur_to縣政中心,dur_to羅東
0,宜蘭市,宜蘭縣宜蘭市農權路三段２７巷７號,131.28,都市：其他:住宅區,NaN,NaN,1111104,土地1建物1車位0,三層,鋼筋混凝土造,1070321.00,289.75,3,2,5,有,無,25000000.00,86281.00,NaN,RPPOMLSKJIHGFBG97DA,265.71,0.00,24.04,有,NaN,2022,11,EkROby4gMjcsIFNlY3Rpb24gMywgTm9uZ3F1YW4gUmQsIF...,5793,2177,5140,10205,875,434,654,1370
1,宜蘭市,宜蘭縣宜蘭市同興街１４６號,36.53,都市：其他:商業區,NaN,NaN,1111101,土地1建物1車位0,二層,鋼筋混凝土加強磚造,NaN,72.23,3,2,3,有,無,3500000.00,48456.00,親友、員工、共有人或其他特殊關係間之交易；頂樓加蓋；,RPPPMLLLJIHGFBG47DA,72.23,0.00,0.00,無,NaN,2022,11,ChIJN2Lv-9HkZzQRypxM56IRi_c,2809,1283,7710,12482,438,325,852,1543
2,員山鄉,宜蘭縣員山鄉大安路９２之２８號,115.66,NaN,特定農業區,甲種建築用地,1111105,土地1建物1車位0,三層,鋼筋混凝土造,860103.00,190.53,5,2,4,有,無,7500000.00,39364.00,壹樓空地；目前屋況有壁癌 滲漏水情形，賣方已由總價中折讓部分價款給買方作為補貼。陽台外推；頂...,RPWNMLNLJIHGFBG18DA,176.43,3.97,10.13,無,NaN,2022,11,ChIJAflWaZ_jZzQRiGeuqAV0Mvc,10359,8331,8304,11486,1189,1082,879,1433
3,三星鄉,宜蘭縣三星鄉健富路二段３４６巷８號,89.00,NaN,特定農業區,甲種建築用地,1111102,土地2建物1車位0,三層,鋼筋混凝土造,1110722.00,160.33,4,2,5,有,無,8080000.00,50396.00,NaN,RPUNMLOLJIHGFAG97DA,145.77,0.00,14.56,無,NaN,2022,11,ChIJ4yeJZBHhZzQR9PyeJmp7ey4,19973,14889,12832,10517,1914,1596,1221,1268
4,員山鄉,宜蘭縣員山鄉員山路一段３６０號,101.15,都市：其他:住宅區,NaN,NaN,1111115,土地2建物1車位0,三層,鋼筋混凝土造,1110714.00,203.51,2,5,3,有,無,22000000.00,108103.00,其他增建:電梯其他增建；,RPRNMLSLJIHGFBG18DA,189.99,0.00,13.52,有,NaN,2022,11,ChIJF6amq4PkZzQRizePLMUguSM,6814,4107,6240,11088,1009,797,613,1330

In [5]:
df.shape

(8993, 37)

In [6]:
# encoding story
story_name = ('一層', '二層', '三層', '四層', '五層')
def cat_story(row):
    for i in range(5):
        if row['story'] == story_name[i]:
            return int(i+1)
    
df['n_story'] = df.apply(lambda row: cat_story(row), axis = 1)

In [7]:
# encoding material
brick = ('加強磚造', '磚造', '加強磚造、木石磚造（磚石造）', '木石磚造',  '木石磚造（磚石造）', '磚石造', '石造', '木造', '土造', '土竹造（土磚混合造）', '土磚石混合造', '鐵筋加強磚造及木造')
rc = ('鋼筋混凝土造（ＲＣ）', '鋼筋混凝土（ＲＣ）', 'ＲＣ造', '鋼筋混凝土造', '鋼筋混凝土', '鋼筋混凝土（ＲＣ）、木構造', '鋼骨鋼筋混凝土造', '鋼筋混凝土、鋼骨造', '鋼骨造', '鋼造')
enf_brick = ('鋼筋混凝土造、加強磚造', '鋼筋混凝土造及鋼筋混凝土加強磚造', '鋼筋混凝土造鋼筋混凝土加強磚造', '鋼筋混凝土加強磚造', '鋼筋混凝土加強磚造、鋼架造', '鐵筋加強磚造、ＲＣ造', 'ＲＣ加強磚造', '鋼筋混凝土加強磚造及鋼筋混凝土造', '鋼筋混凝土加強磚造﹒鋼筋混凝土造', '鐵筋加強磚造')
iron = ('鋼鐵造、鋼架造有牆', '鋼鐵有牆造')

material_catlist = (brick, rc, enf_brick, iron)
material_namelist = ('brick', 'rc', 'enf_brick', 'iron')

def cat_material(row):
    for pair in zip(material_catlist, material_namelist):
        if row['material'] in pair[0]:
            return pair[1]

df['n_material'] = df.apply(lambda row: cat_material(row), axis = 1)

In [8]:
df.groupby(['urb_zoning']).size()

urb_zoning
住                           2371
其他                            18
商                            151
工                             11
農                            312
都市：其他:                        11
都市：其他:乙種工業區                    2
都市：其他:人行步道                     1
都市：其他:住                        2
都市：其他:住宅區                   1049
都市：其他:住宅區(住一)                  5
都市：其他:住宅區(住三)                  5
都市：其他:住宅區(住二)                 18
都市：其他:住宅區(住六)                  3
都市：其他:住宅區(住四)                  3
都市：其他:保護區                     13
都市：其他:兒童遊樂場                    1
都市：其他:公園用地                     1
都市：其他:公墓用地                     1
都市：其他:商業區                     55
都市：其他:學校用地                     1
都市：其他:工商綜合區(一)                 2
都市：其他:工業區                      5
都市：其他:廣場用地                     1
都市：其他:批發市場用地                   1
都市：其他:河川區                      2
都市：其他:生物醫學產業特定專用區(二)           4
都市：其他:第一種住宅區                   1
都市：其他:第一種遊憩服務設施                1
都市：其他:第三種住宅區。                  4
都市：其他:第二種住宅區                  18
都市：其他:第二種商業區                   1
都市：其他:第二種遊憩服務設施                1
都市：其他:農                        1
都市：其他:農業區                    195
都市：其他:道路用地                    45
都市：其他:部分商業區部分住宅區               1
都市：其他:酒業文化專用區                  1
都市：商                           1
非都市：特定農業區 ; 非都市編定：甲種建築用地       5
dtype: int64

In [9]:
res = ('住', '都市：其他:住', '都市：其他:住宅區', '都市：其他:住宅區(住一)', '都市：其他:住宅區(住二)', '都市：其他:住宅區(住三)', '都市：其他:住宅區(住四)', '都市：其他:住宅區(住六)', '都市：其他:第一種住宅區', '都市：其他:第三種住宅區。', '都市：其他:第二種住宅區', '都市：其他:部分商業區部分住宅區')
comm = ('商', '都市：商', '都市：其他:第二種商業區', '都市：其他:工業區', '都市：其他:工商綜合區(一)', '都市：其他:商業區')
ind = ('工', '都市：其他:工業區', '都市：其他:乙種工業區')
agr = ('農', '都市：其他:農業區', '都市：其他:農')
env = ('都市：其他:保護區', '都市：其他:河川區')
urb_zone_catlist = (res, comm, ind, agr, env)
urb_zone_namelist = ('res', 'comm', 'ind', 'agr', 'env')

def cat_urb_zoning(row):
    for pair in zip(urb_zone_catlist, urb_zone_namelist):
        if row['urb_zoning'] in pair[0]:
            return pair[1]
    return np.nan

df['n_urb_zoning'] = df.apply(lambda row: cat_urb_zoning(row), axis = 1)

In [10]:
df = df.drop(['nurb_land'], axis=1)

In [11]:
nurb_zoning_name = ('一般農業區', '山坡地保育區', '工業區', '特定農業區', '鄉村區', '風景區')

In [12]:
def cat_urban(row):
    if not pd.isna(row['urb_zoning']) and row['urb_zoning'] != '非都市：特定農業區 ; 非都市編定：甲種建築用地':
        return 1
    else:
        return 0
    
df['d_urban'] = df.apply(lambda row: cat_urban(row), axis = 1)

In [13]:
df = df.rename(columns={'d_elevator': 'old_d_elevator'})
def get_d_elevator(row):
    if row['old_d_elevator'] == '有':
        return 1
    elif row['old_d_elevator'] == '無':
        return 0
    else:
        return np.nan
df['d_elevator'] = df.apply(lambda row: get_d_elevator(row), axis = 1)

In [14]:
def get_completion_year(row):
    if row['completion_date'] >= 100000:
        return (row['completion_date']//10000) + 1911
    if row['completion_date'] < 100:
        return row['completion_date'] + 1911
    
df['completion_year'] = df.apply(lambda row: get_completion_year(row), axis = 1)
sum(df['completion_year'].isnull())

257

In [15]:
df['completion_year'].describe()

count   8736.00
mean    2001.59
std       18.72
min     1925.00
25%     1981.00
50%     2010.00
75%     2019.00
max     2022.00
Name: completion_year, dtype: float64

In [16]:
df['age'] = df.apply(lambda row: row['year']-row['completion_year'], axis=1)
df['d_presale'] = df.apply(lambda row: 1 if row['age'] < 0 else 0, axis = 1) # dummy for presale house
df['age'] = df.apply(lambda row: 0 if row['age'] < 0 else row['age'], axis = 1)
df['age'].describe()

count   8736.00
mean      18.62
std       18.57
min        0.00
25%        1.00
50%       10.00
75%       38.00
max       96.00
Name: age, dtype: float64

In [17]:
sum(df['d_comp'].isnull()) # check for missing values
df = df.rename(columns={'d_comp': 'old_d_comp'})
df['d_comp'] = df.apply(lambda row: 1 if row['old_d_comp'] == '有' else 0, axis = 1)
df['d_comp'].describe()

count   8993.00
mean       0.97
std        0.16
min        0.00
25%        1.00
50%        1.00
75%        1.00
max        1.00
Name: d_comp, dtype: float64

In [18]:
sum(df['d_manager'].isnull()) # check for missing values
df = df.rename(columns={'d_manager': 'old_d_manager'})
def get_d_manager(row):
    if row['old_d_manager'] == '有':
        return 1
    elif row['old_d_manager'] == '無':
        return 0
    else:
        return np.nan
df['d_manager'] = df.apply(lambda row: get_d_manager(row), axis = 1)
df['d_manager'].describe()

count   8993.00
mean       0.02
std        0.15
min        0.00
25%        0.00
50%        0.00
75%        0.00
max        1.00
Name: d_manager, dtype: float64

In [19]:
# special relationships
df['note'] = df['note'].fillna(value = '')
df['d_spec_rel'] = df.apply(lambda row: 1 if ('親友、員工、共有人或其他特殊關係間之交易' in row['note']) else 0, axis = 1)
df['d_spec_rel'].describe()

count   8993.00
mean       0.04
std        0.19
min        0.00
25%        0.00
50%        0.00
75%        0.00
max        1.00
Name: d_spec_rel, dtype: float64

In [20]:
df

,town,address,land_area,urb_zoning,nurb_zoning,date,object_num,story,material,completion_date,building_area,n_bed,n_hall,n_bath,old_d_comp,old_d_manager,price,unitprice,note,serialnumber,main_area,aux_area,balcony_area,old_d_elevator,trans_num,year,month,place_id,dist_to四城,dist_to宜蘭,dist_to縣政中心,dist_to羅東,dur_to四城,dur_to宜蘭,dur_to縣政中心,dur_to羅東,n_story,n_material,n_urb_zoning,d_urban,d_elevator,completion_year,age,d_presale,d_comp,d_manager,d_spec_rel
0,宜蘭市,宜蘭縣宜蘭市農權路三段２７巷７號,131.28,都市：其他:住宅區,NaN,1111104,土地1建物1車位0,三層,鋼筋混凝土造,1070321.00,289.75,3,2,5,有,無,25000000.00,86281.00,,RPPOMLSKJIHGFBG97DA,265.71,0.00,24.04,有,NaN,2022,11,EkROby4gMjcsIFNlY3Rpb24gMywgTm9uZ3F1YW4gUmQsIF...,5793,2177,5140,10205,875,434,654,1370,3.00,rc,res,1,1.00,2018.00,4.00,0,1,0,0
1,宜蘭市,宜蘭縣宜蘭市同興街１４６號,36.53,都市：其他:商業區,NaN,1111101,土地1建物1車位0,二層,鋼筋混凝土加強磚造,NaN,72.23,3,2,3,有,無,3500000.00,48456.00,親友、員工、共有人或其他特殊關係間之交易；頂樓加蓋；,RPPPMLLLJIHGFBG47DA,72.23,0.00,0.00,無,NaN,2022,11,ChIJN2Lv-9HkZzQRypxM56IRi_c,2809,1283,7710,12482,438,325,852,1543,2.00,enf_brick,comm,1,0.00,NaN,NaN,0,1,0,1
2,員山鄉,宜蘭縣員山鄉大安路９２之２８號,115.66,NaN,特定農業區,1111105,土地1建物1車位0,三層,鋼筋混凝土造,860103.00,190.53,5,2,4,有,無,7500000.00,39364.00,壹樓空地；目前屋況有壁癌 滲漏水情形，賣方已由總價中折讓部分價款給買方作為補貼。陽台外推；頂...,RPWNMLNLJIHGFBG18DA,176.43,3.97,10.13,無,NaN,2022,11,ChIJAflWaZ_jZzQRiGeuqAV0Mvc,10359,8331,8304,11486,1189,1082,879,1433,3.00,rc,NaN,0,0.00,1997.00,25.00,0,1,0,0
3,三星鄉,宜蘭縣三星鄉健富路二段３４６巷８號,89.00,NaN,特定農業區,1111102,土地2建物1車位0,三層,鋼筋混凝土造,1110722.00,160.33,4,2,5,有,無,8080000.00,50396.00,,RPUNMLOLJIHGFAG97DA,145.77,0.00,14.56,無,NaN,2022,11,ChIJ4yeJZBHhZzQR9PyeJmp7ey4,19973,14889,12832,10517,1914,1596,1221,1268,3.00,rc,NaN,0,0.00,2022.00,0.00,0,1,0,0
4,員山鄉,宜蘭縣員山鄉員山路一段３６０號,101.15,都市：其他:住宅區,NaN,1111115,土地2建物1車位0,三層,鋼筋混凝土造,1110714.00,203.51,2,5,3,有,無,22000000.00,108103.00,其他增建:電梯其他增建；,RPRNMLSLJIHGFBG18DA,189.99,0.00,13.52,有,NaN,2022,11,ChIJF6amq4PkZzQRizePLMUguSM,6814,4107,6240,11088,1009,797,613,1330,3.00,rc,res,1,1.00,2022.00,0.00,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8988,員山鄉,宜蘭縣員山鄉榮光路２６４之１號,82.00,NaN,鄉村區,1070129,土地1建物1車位0,二層,鋼筋混凝土加強磚造,690131.00,85.79,3,1,2,有,無,4100000.00,47791.00,,RPPNMLNKKHNFFBG77CA,85.79,0.00,0.00,NaN,NaN,2018,1,ChIJxRAmRcfjZzQRqICYdl4csPc,12701,9833,10124,11566,1376,1144,802,1369,2.00,enf_brick,NaN,0,NaN,1980.00,38.00,0,1,0,0
8989,頭城鎮,宜蘭縣頭城鎮新興路231-30號,100.32,住,NaN,1070104,土地2建物1車位0,二層,鋼筋混凝土加強磚造,701224.00,133.76,4,2,2,有,無,7000000.00,52333.00,三樓加蓋面積64.5平方公尺,RPUNMLMKLHNFFBG38DA,133.76,0.00,0.00,NaN,NaN,2018,1,ChIJs_e1g1z3ZzQRMgte3FZRAuY,11639,15218,19493,25038,1083,1373,1441,1703,2.00,enf_brick,res,1,NaN,1981.00,37.00,0,1,0,0
8990,五結鄉,宜蘭縣五結鄉仁五路一段５１巷２號,158.32,農,NaN,1070123,土地3建物1車位0,三層,見其他登記事項,1040708.00,210.29,4,2,5,有,無,11400000.00,54211.00,,RPWNMLRLKHNFFAG88CA,194.65,0.00,15.64,NaN,NaN,2018,1,Ek1Oby4gMiwgTGFuZSA1MSwgU2VjdGlvbiAxLCBSZW53dS...,13466,11197,6090,2758,1066,1047,646,487,3.00,None,agr,1,NaN,2015.00,3.00,0,1,0,0
8991,冬山鄉,宜蘭縣冬山鄉寶和路１７６巷１２號,92.95,NaN,特定農業區,1070107,土地0建物1車位0,三層,見其他登記事項,1040709.00,172.31,4,2,4,有,無,8550000.00,49620.00,,RPRNMLOKKHNFFAG97CA,157.50,0.00,14.81,NaN,NaN,2018,1,ChIJcVqaZqnnZzQRR3UWu4A-tbQ,21862,15715,12304,6706,1927,1896,1420,844,3.00,None,NaN,0,NaN,2015.00,3.00,0,1,0,0
8992,五結鄉,宜蘭縣五結鄉新店路１４號,289.50,NaN,鄉村區,1070123,土地2建物1車位0,一層,磚造,671121.00,90.31,6,2,4,有,無,6600000.00,73082.00,,RPROMLNKKHNFFAG97CA,76.00,14.31,0.00,NaN,NaN,2018,1,ChIJMzJARkzvZzQRCwPO94giSUU,16602,15767,12007,6126,1461,1449,1102,769,1.00,brick,NaN,0,NaN,1978.00,40.00,0,1,0,0

In [21]:
# presale house from note
df['d_presale_2'] = df.apply(lambda row: 1 if ('預售屋、或土地及建物分件登記案件' in row['note']) else 0, axis = 1)
df['d_presale_2'].describe()

count   8993.00
mean       0.07
std        0.25
min        0.00
25%        0.00
50%        0.00
75%        0.00
max        1.00
Name: d_presale_2, dtype: float64

In [22]:
df['d_presale'].describe()

count   8993.00
mean       0.12
std        0.32
min        0.00
25%        0.00
50%        0.00
75%        0.00
max        1.00
Name: d_presale, dtype: float64

In [23]:
df['d_notreg'] = df.apply(lambda row: 1 if '未登記建物' in row['note'] else 0, axis = 1)
df['d_notreg'].describe()

count   8993.00
mean       0.06
std        0.24
min        0.00
25%        0.00
50%        0.00
75%        0.00
max        1.00
Name: d_notreg, dtype: float64

In [24]:
df['d_hotspring'] = df.apply(lambda row: 1 if '溫泉宅' in row['note'] else 0, axis = 1)
df['d_hotspring'].describe()

count   8993.00
mean       0.00
std        0.05
min        0.00
25%        0.00
50%        0.00
75%        0.00
max        1.00
Name: d_hotspring, dtype: float64

In [25]:
df['d_leak'] = df.apply(lambda row: 1 if '漏水' in row['note'] else 0, axis = 1)
df['d_leak'].describe()

count   8993.00
mean       0.00
std        0.06
min        0.00
25%        0.00
50%        0.00
75%        0.00
max        1.00
Name: d_leak, dtype: float64

In [26]:
df['d_reno'] = df.apply(lambda row: 1 if '含裝潢費' in row['note'] else 0, axis = 1)
df['d_leak'].describe()

count   8993.00
mean       0.00
std        0.06
min        0.00
25%        0.00
50%        0.00
75%        0.00
max        1.00
Name: d_leak, dtype: float64

In [27]:
df.columns

Index(['town', 'address', 'land_area', 'urb_zoning', 'nurb_zoning', 'date',
       'object_num', 'story', 'material', 'completion_date', 'building_area',
       'n_bed', 'n_hall', 'n_bath', 'old_d_comp', 'old_d_manager', 'price',
       'unitprice', 'note', 'serialnumber', 'main_area', 'aux_area',
       'balcony_area', 'old_d_elevator', 'trans_num', 'year', 'month',
       'place_id', 'dist_to四城', 'dist_to宜蘭', 'dist_to縣政中心', 'dist_to羅東',
       'dur_to四城', 'dur_to宜蘭', 'dur_to縣政中心', 'dur_to羅東', 'n_story',
       'n_material', 'n_urb_zoning', 'd_urban', 'd_elevator',
       'completion_year', 'age', 'd_presale', 'd_comp', 'd_manager',
       'd_spec_rel', 'd_presale_2', 'd_notreg', 'd_hotspring', 'd_leak',
       'd_reno'],
      dtype='object')

In [28]:
df = df[['town', 'address', 'land_area', 'object_num', 'building_area',
       'n_bed', 'n_hall', 'n_bath', 'price', 'unitprice', 'main_area', 'aux_area',
       'balcony_area', 'trans_num', 'year', 'month', 'dist_to四城', 'dist_to宜蘭', 'dist_to縣政中心', 'dist_to羅東',
       'n_story','n_material', 'n_urb_zoning', 'd_urban', 'd_elevator',
       'completion_year', 'age', 'd_presale', 'd_comp', 'd_manager', 'd_spec_rel',
       'd_presale_2', 'd_notreg', 'd_hotspring', 'd_leak', 'd_reno']]
df.columns

Index(['town', 'address', 'land_area', 'object_num', 'building_area', 'n_bed',
       'n_hall', 'n_bath', 'price', 'unitprice', 'main_area', 'aux_area',
       'balcony_area', 'trans_num', 'year', 'month', 'dist_to四城', 'dist_to宜蘭',
       'dist_to縣政中心', 'dist_to羅東', 'n_story', 'n_material', 'n_urb_zoning',
       'd_urban', 'd_elevator', 'completion_year', 'age', 'd_presale',
       'd_comp', 'd_manager', 'd_spec_rel', 'd_presale_2', 'd_notreg',
       'd_hotspring', 'd_leak', 'd_reno'],
      dtype='object')

In [29]:
df.describe()

,land_area,building_area,n_bed,n_hall,n_bath,price,unitprice,main_area,aux_area,balcony_area,trans_num,year,month,dist_to四城,dist_to宜蘭,dist_to縣政中心,dist_to羅東,n_story,d_urban,d_elevator,completion_year,age,d_presale,d_comp,d_manager,d_spec_rel,d_presale_2,d_notreg,d_hotspring,d_leak,d_reno
count,8993.00,8993.00,8993.00,8993.00,8993.00,8993.00,8992.00,8993.00,8993.00,8993.00,1126.00,8993.00,8993.00,8993.00,8993.00,8993.00,8993.00,8991.00,8993.00,5639.00,8736.00,8736.00,8993.00,8993.00,8993.00,8993.00,8993.00,8993.00,8993.00,8993.00,8993.00
mean,127.09,166.16,3.68,1.92,3.31,8867553.38,55156.62,153.87,2.31,9.37,303.04,2020.07,6.65,12974.75,10463.56,9310.39,9178.09,2.76,0.48,0.08,2001.59,18.62,0.12,0.97,0.02,0.04,0.07,0.06,0.00,0.00,0.00
std,273.19,64.75,1.41,0.73,1.40,6211912.95,44882.17,58.51,6.76,9.26,170.24,1.31,3.37,7024.94,6561.45,5107.41,5897.74,0.71,0.50,0.28,18.72,18.57,0.32,0.16,0.15,0.19,0.25,0.24,0.05,0.06,0.05
min,4.34,1.86,0.00,0.00,0.00,50000.00,1121.00,0.00,0.00,0.00,1.00,2018.00,1.00,118.00,161.00,90.00,177.00,1.00,0.00,0.00,1925.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,84.48,121.72,3.00,2.00,2.00,5700000.00,40727.50,117.83,0.00,0.00,164.00,2019.00,4.00,6583.00,5046.00,5704.00,4712.00,2.00,0.00,0.00,1981.00,1.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,101.67,167.61,4.00,2.00,3.00,8000000.00,49549.00,153.65,0.00,9.98,301.00,2020.00,7.00,13105.00,10135.00,8178.00,8669.00,3.00,0.00,0.00,2010.00,10.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
75%,124.64,197.60,4.00,2.00,4.00,10800000.00,61312.50,179.94,0.00,15.25,437.00,2021.00,10.00,18237.00,14146.00,12309.00,12449.00,3.00,1.00,0.00,2019.00,38.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
max,17374.66,1066.49,18.00,8.00,18.00,270000000.00,2043165.00,1040.79,119.81,131.11,673.00,2022.00,12.00,62205.00,57255.00,61531.00,67076.00,5.00,1.00,1.00,2022.00,96.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00

In [30]:
np.round(df.describe(), 2).T

,count,mean,std,min,25%,50%,75%,max
land_area,8993.00,127.09,273.19,4.34,84.48,101.67,124.64,17374.66
building_area,8993.00,166.16,64.75,1.86,121.72,167.61,197.60,1066.49
n_bed,8993.00,3.68,1.41,0.00,3.00,4.00,4.00,18.00
n_hall,8993.00,1.92,0.73,0.00,2.00,2.00,2.00,8.00
n_bath,8993.00,3.31,1.40,0.00,2.00,3.00,4.00,18.00
price,8993.00,8867553.38,6211912.95,50000.00,5700000.00,8000000.00,10800000.00,270000000.00
unitprice,8992.00,55156.62,44882.17,1121.00,40727.50,49549.00,61312.50,2043165.00
main_area,8993.00,153.87,58.51,0.00,117.83,153.65,179.94,1040.79
aux_area,8993.00,2.31,6.76,0.00,0.00,0.00,0.00,119.81
balcony_area,8993.00,9.37,9.26,0.00,0.00,9.98,15.25,131.11
trans_num,1126.00,303.04,170.24,1.00,164.00,301.00,437.00,673.00
year,8993.00,2020.07,1.31,2018.00,2019.00,2020.00,2021.00,2022.00
month,8993.00,6.65,3.37,1.00,4.00,7.00,10.00,12.00
dist_to四城,8993.00,12974.75,7024.94,118.00,6583.00,13105.00,18237.00,62205.00
dist_to宜蘭,8993.00,10463.56,6561.45,161.00,5046.00,10135.00,14146.00,57255.00
dist_to縣政中心,8993.00,9310.39,5107.41,90.00,5704.00,8178.00,12309.00,61531.00
dist_to羅東,8993.00,9178.09,5897.74,177.00,4712.00,8669.00,12449.00,67076.00
n_story,8991.00,2.76,0.71,1.00,2.00,3.00,3.00,5.00
d_urban,8993.00,0.48,0.50,0.00,0.00,0.00,1.00,1.00
d_elevator,5639.00,0.08,0.28,0.00,0.00,0.00,0.00,1.00
completion_year,8736.00,2001.59,18.72,1925.00,1981.00,2010.00,2019.00,2022.00
age,8736.00,18.62,18.57,0.00,1.00,10.00,38.00,96.00
d_presale,8993.00,0.12,0.32,0.00,0.00,0.00,0.00,1.00
d_comp,8993.00,0.97,0.16,0.00,1.00,1.00,1.00,1.00
d_manager,8993.00,0.02,0.15,0.00,0.00,0.00,0.00,1.00
d_spec_rel,8993.00,0.04,0.19,0.00,0.00,0.00,0.00,1.00
d_presale_2,8993.00,0.07,0.25,0.00,0.00,0.00,0.00,1.00
d_notreg,8993.00,0.06,0.24,0.00,0.00,0.00,0.00,1.00
d_hotspring,8993.00,0.00,0.05,0.00,0.00,0.00,0.00,1.00
d_leak,8993.00,0.00,0.06,0.00,0.00,0.00,0.00,1.00
d_reno,8993.00,0.00,0.05,0.00,0.00,0.00,0.00,1.00

In [31]:
np.round(df.describe(), 2).T[['count','mean', 'std', 'min', 'max']]

                  count       mean        std      min          max
land_area       8993.00     127.09     273.19     4.34     17374.66
building_area   8993.00     166.16      64.75     1.86      1066.49
n_bed           8993.00       3.68       1.41     0.00        18.00
n_hall          8993.00       1.92       0.73     0.00         8.00
n_bath          8993.00       3.31       1.40     0.00        18.00
price           8993.00 8867553.38 6211912.95 50000.00 270000000.00
unitprice       8992.00   55156.62   44882.17  1121.00   2043165.00
main_area       8993.00     153.87      58.51     0.00      1040.79
aux_area        8993.00       2.31       6.76     0.00       119.81
balcony_area    8993.00       9.37       9.26     0.00       131.11
trans_num       1126.00     303.04     170.24     1.00       673.00
year            8993.00    2020.07       1.31  2018.00      2022.00
month           8993.00       6.65       3.37     1.00        12.00
dist_to四城       8993.00   12974.75    7024.94   118.00     62205.00
dist_to宜蘭       8993.00   10463.56    6561.45   161.00     57255.00
dist_to縣政中心     8993.00    9310.39    5107.41    90.00     61531.00
dist_to羅東       8993.00    9178.09    5897.74   177.00     67076.00
n_story         8991.00       2.76       0.71     1.00         5.00
d_urban         8993.00       0.48       0.50     0.00         1.00
d_elevator      5639.00       0.08       0.28     0.00         1.00
completion_year 8736.00    2001.59      18.72  1925.00      2022.00
age             8736.00      18.62      18.57     0.00        96.00
d_presale       8993.00       0.12       0.32     0.00         1.00
d_comp          8993.00       0.97       0.16     0.00         1.00
d_manager       8993.00       0.02       0.15     0.00         1.00
d_spec_rel      8993.00       0.04       0.19     0.00         1.00
d_presale_2     8993.00       0.07       0.25     0.00         1.00
d_notreg        8993.00       0.06       0.24     0.00         1.00
d_hotspring     8993.00       0.00       0.05     0.00         1.00
d_leak          8993.00       0.00       0.06     0.00         1.00
d_reno          8993.00       0.00       0.05     0.00         1.00

In [32]:
df.to_csv('11Input/02DataProcessed/cleaned.csv', index=False)