In [1]:
import pandas as pd
import numpy as np

In [2]:
#Set PANDAS to show all columns in DataFrame
pd.set_option('display.max_columns', None)

In [3]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [4]:
df = pd.read_csv('11Input/02DataProcessed/distanced.csv')
df.head()

,town,address,land_area,urb_zoning,nurb_zoning,nurb_land,date,object_num,story,material,completion_date,building_area,n_bed,n_hall,n_bath,d_comp,d_manager,price,unitprice,note,serialnumber,main_area,aux_area,balcony_area,d_elevator,trans_num,year,month,place_id,dist_to四城,dist_to宜蘭,dist_to縣政中心,dist_to羅東,dur_to四城,dur_to宜蘭,dur_to縣政中心,dur_to羅東
0,五結鄉,宜蘭縣五結鄉孝威路３３３巷９號,107.93,NaN,鄉村區,乙種建築用地,1111202,土地3建物1車位0,三層,鋼筋混凝土造,1050829.00,182.43,4,3,3,有,無,9000000.00,49334.00,NaN,RPQOMLOKKIHGFAG67DA,169.09,0.00,13.34,無,NaN,2022,12,ChIJq45Z52HvZzQRAUyrHefRVX8,14608,12338,8568,5998,1185,1167,721,708
1,宜蘭市,宜蘭縣宜蘭市女中路三段５８１號,87.62,住,NaN,NaN,1111201,土地1建物1車位0,四層,鋼筋混凝土造,880127.00,257.08,5,3,4,有,無,15800000.00,61459.00,其他增建:1-3樓後方其他增建；,RPQRMLOKKIHGFBG08DA,216.00,13.99,27.09,無,NaN,2022,12,ChIJ_W0WLZHkZzQRugzY7vMVcGs,5822,3156,5548,10613,842,576,683,1399
2,冬山鄉,宜蘭縣冬山鄉永興路二段９１巷１弄５２之１２號,145.54,NaN,特定農業區,甲種建築用地,1111206,土地3建物1車位0,三層,鋼筋混凝土造,1050627.00,176.94,4,2,5,有,無,11000000.00,62168.00,NaN,RPUOMLPKKIHGFAG18DA,162.12,0.00,14.82,無,128.00,2022,12,ChIJNYDmW_DmZzQRX45dA0Kl6Gg,16533,12803,9392,5216,1907,1690,1215,768
3,三星鄉,宜蘭縣三星鄉大坑三路８８號,143.50,NaN,特定農業區,甲種建築用地,1111203,土地1建物1車位0,三層,鋼筋混凝土造,810730.00,159.27,4,2,3,有,無,6900000.00,43323.00,其他增建；,RPVOMLPKKIHGFAG28DA,159.27,0.00,0.00,無,129.00,2022,12,Ej1Oby4gODgsIERha2VuZyBSZCwgU2FueGluZyBUb3duc2...,21539,16472,14398,10164,2086,1796,1397,1392
4,三星鄉,宜蘭縣三星鄉上將路一段３３巷３８弄２５號,70.65,NaN,特定農業區,甲種建築用地,1111201,土地5建物1車位0,三層,鋼筋混凝土造,1110805.00,162.28,3,2,4,有,無,9150000.00,56384.00,NaN,RPUOMLKLKIHGFAG87EA,146.73,0.00,15.55,無,135.00,2022,12,ElVOby4gMzgsIExhbmUgMzMsIFNlY3Rpb24gMSwgU2hhbm...,12162,8431,5021,4429,1193,976,500,605

In [5]:
df.shape

(9377, 37)

In [6]:
# encoding area
df['percent_aux'] = df.apply(lambda row: 100*round(row['aux_area'] / row['building_area'], 4), axis = 1)
df['percent_balcony'] = df.apply(lambda row: 100*round(row['balcony_area'] / row['building_area'], 4), axis = 1)

In [7]:
# encoding story
story_name = ('一層', '二層', '三層', '四層', '五層')
def cat_story(row):
    for i in range(5):
        if row['story'] == story_name[i]:
            return int(i+1)
    
df['n_story'] = df.apply(lambda row: cat_story(row), axis = 1)

In [8]:
# encoding material
brick = ('加強磚造', '磚造', '加強磚造、木石磚造（磚石造）', '木石磚造',  '木石磚造（磚石造）', '磚石造', '石造', '木造', '土造', '土竹造（土磚混合造）', '土磚石混合造', '鐵筋加強磚造及木造')
rc = ('鋼筋混凝土造（ＲＣ）', '鋼筋混凝土（ＲＣ）', 'ＲＣ造', '鋼筋混凝土造', '鋼筋混凝土', '鋼筋混凝土（ＲＣ）、木構造', '鋼骨鋼筋混凝土造', '鋼筋混凝土、鋼骨造', '鋼骨造', '鋼造')
enf_brick = ('鋼筋混凝土造、加強磚造', '鋼筋混凝土造及鋼筋混凝土加強磚造', '鋼筋混凝土造鋼筋混凝土加強磚造', '鋼筋混凝土加強磚造', '鋼筋混凝土加強磚造、鋼架造', '鐵筋加強磚造、ＲＣ造', 'ＲＣ加強磚造', '鋼筋混凝土加強磚造及鋼筋混凝土造', '鋼筋混凝土加強磚造﹒鋼筋混凝土造', '鐵筋加強磚造')
iron = ('鋼鐵造、鋼架造有牆', '鋼鐵有牆造')

material_catlist = (brick, rc, enf_brick, iron)
material_namelist = ('brick', 'rc', 'enf_brick', 'iron')

def cat_material(row):
    for pair in zip(material_catlist, material_namelist):
        if row['material'] in pair[0]:
            return pair[1]

df['n_material'] = df.apply(lambda row: cat_material(row), axis = 1)

In [9]:
df.groupby(['urb_zoning']).size()

urb_zoning
住                           2506
其他                            18
商                            164
工                             11
農                            332
都市：其他:                        11
都市：其他:乙種工業區                    2
都市：其他:人行步道                     1
都市：其他:住                        2
都市：其他:住宅區                   1059
都市：其他:住宅區(住一)                  5
都市：其他:住宅區(住三)                  5
都市：其他:住宅區(住二)                 18
都市：其他:住宅區(住六)                  3
都市：其他:住宅區(住四)                  3
都市：其他:保護區                     13
都市：其他:兒童遊樂場                    1
都市：其他:公園用地                     1
都市：其他:公墓用地                     1
都市：其他:商業區                     56
都市：其他:學校用地                     1
都市：其他:工商綜合區(一)                 3
都市：其他:工業區                      5
都市：其他:廣場用地                     1
都市：其他:批發市場用地                   1
都市：其他:河川區                      2
都市：其他:生物醫學產業特定專用區(二)           4
都市：其他:第一種住宅區                   1
都市：其他:第一種遊憩服務設施                1
都市：其他:第三種住宅區。                  4
都市：其他:第二種住宅區                  18
都市：其他:第二種商業區                   1
都市：其他:第二種遊憩服務設施                1
都市：其他:農                        1
都市：其他:農業區                    195
都市：其他:道路用地                    45
都市：其他:部分商業區部分住宅區               1
都市：其他:酒業文化專用區                  1
都市：商                           1
非都市：特定農業區 ; 非都市編定：甲種建築用地       5
dtype: int64

In [10]:
res = ('住', '都市：其他:住', '都市：其他:住宅區', '都市：其他:住宅區(住一)', '都市：其他:住宅區(住二)', '都市：其他:住宅區(住三)', '都市：其他:住宅區(住四)', '都市：其他:住宅區(住六)', '都市：其他:第一種住宅區', '都市：其他:第三種住宅區。', '都市：其他:第二種住宅區', '都市：其他:部分商業區部分住宅區')
comm = ('商', '都市：商', '都市：其他:第二種商業區', '都市：其他:工業區', '都市：其他:工商綜合區(一)', '都市：其他:商業區')
ind = ('工', '都市：其他:工業區', '都市：其他:乙種工業區')
agr = ('農', '都市：其他:農業區', '都市：其他:農')
env = ('都市：其他:保護區', '都市：其他:河川區')
urb_zone_catlist = (res, comm, ind, agr, env)
urb_zone_namelist = ('res', 'comm', 'ind', 'agr', 'env')

def cat_urb_zoning(row):
    for pair in zip(urb_zone_catlist, urb_zone_namelist):
        if row['urb_zoning'] in pair[0]:
            return pair[1]
    return np.nan

df['n_urb_zoning'] = df.apply(lambda row: cat_urb_zoning(row), axis = 1)

In [11]:
df = df.drop(['nurb_land'], axis=1)

In [12]:
nurb_zoning_name = ('一般農業區', '山坡地保育區', '工業區', '特定農業區', '鄉村區', '風景區')

In [13]:
def cat_urban(row):
    if not pd.isna(row['urb_zoning']) and row['urb_zoning'] != '非都市：特定農業區 ; 非都市編定：甲種建築用地':
        return 1
    else:
        return 0
    
df['d_urban'] = df.apply(lambda row: cat_urban(row), axis = 1)

In [14]:
df = df.rename(columns={'d_elevator': 'old_d_elevator'})
def get_d_elevator(row):
    if row['old_d_elevator'] == '有':
        return 1
    elif row['old_d_elevator'] == '無':
        return 0
    else:
        return np.nan
df['d_elevator'] = df.apply(lambda row: get_d_elevator(row), axis = 1)

In [15]:
def get_completion_year(row):
    if row['completion_date'] >= 100000:
        return (row['completion_date']//10000) + 1911
    if row['completion_date'] < 100:
        return row['completion_date'] + 1911
    
df['completion_year'] = df.apply(lambda row: get_completion_year(row), axis = 1)
sum(df['completion_year'].isnull())

266

In [16]:
df['completion_year'].describe()

count   9111.00
mean    2001.81
std       18.76
min     1925.00
25%     1981.00
50%     2011.00
75%     2019.00
max     2022.00
Name: completion_year, dtype: float64

In [17]:
df['age'] = df.apply(lambda row: row['year']-row['completion_year'], axis=1)
df['d_presale'] = df.apply(lambda row: 1 if row['age'] < 0 else 0, axis = 1) # dummy for presale house
df['age'] = df.apply(lambda row: 0 if row['age'] < 0 else row['age'], axis = 1)
df['age'].describe()

count   9111.00
mean      18.47
std       18.60
min        0.00
25%        1.00
50%        9.00
75%       38.00
max       96.00
Name: age, dtype: float64

In [18]:
sum(df['d_comp'].isnull()) # check for missing values
df = df.rename(columns={'d_comp': 'old_d_comp'})
df['d_comp'] = df.apply(lambda row: 1 if row['old_d_comp'] == '有' else 0, axis = 1)
df['d_comp'].describe()

count   9377.00
mean       0.96
std        0.18
min        0.00
25%        1.00
50%        1.00
75%        1.00
max        1.00
Name: d_comp, dtype: float64

In [19]:
sum(df['d_manager'].isnull()) # check for missing values
df = df.rename(columns={'d_manager': 'old_d_manager'})
def get_d_manager(row):
    if row['old_d_manager'] == '有':
        return 1
    elif row['old_d_manager'] == '無':
        return 0
    else:
        return np.nan
df['d_manager'] = df.apply(lambda row: get_d_manager(row), axis = 1)
df['d_manager'].describe()

count   9377.00
mean       0.02
std        0.15
min        0.00
25%        0.00
50%        0.00
75%        0.00
max        1.00
Name: d_manager, dtype: float64

In [20]:
# special relationships
df['note'] = df['note'].fillna(value = '')
df['d_spec_rel'] = df.apply(lambda row: 1 if ('親友、員工、共有人或其他特殊關係間之交易' in row['note']) else 0, axis = 1)
df['d_spec_rel'].describe()

count   9377.00
mean       0.04
std        0.20
min        0.00
25%        0.00
50%        0.00
75%        0.00
max        1.00
Name: d_spec_rel, dtype: float64

In [21]:
df

,town,address,land_area,urb_zoning,nurb_zoning,date,object_num,story,material,completion_date,building_area,n_bed,n_hall,n_bath,old_d_comp,old_d_manager,price,unitprice,note,serialnumber,main_area,aux_area,balcony_area,old_d_elevator,trans_num,year,month,place_id,dist_to四城,dist_to宜蘭,dist_to縣政中心,dist_to羅東,dur_to四城,dur_to宜蘭,dur_to縣政中心,dur_to羅東,percent_aux,percent_balcony,n_story,n_material,n_urb_zoning,d_urban,d_elevator,completion_year,age,d_presale,d_comp,d_manager,d_spec_rel
0,五結鄉,宜蘭縣五結鄉孝威路３３３巷９號,107.93,NaN,鄉村區,1111202,土地3建物1車位0,三層,鋼筋混凝土造,1050829.00,182.43,4,3,3,有,無,9000000.00,49334.00,,RPQOMLOKKIHGFAG67DA,169.09,0.00,13.34,無,NaN,2022,12,ChIJq45Z52HvZzQRAUyrHefRVX8,14608,12338,8568,5998,1185,1167,721,708,0.00,7.31,3.00,rc,NaN,0,0.00,2016.00,6.00,0,1,0,0
1,宜蘭市,宜蘭縣宜蘭市女中路三段５８１號,87.62,住,NaN,1111201,土地1建物1車位0,四層,鋼筋混凝土造,880127.00,257.08,5,3,4,有,無,15800000.00,61459.00,其他增建:1-3樓後方其他增建；,RPQRMLOKKIHGFBG08DA,216.00,13.99,27.09,無,NaN,2022,12,ChIJ_W0WLZHkZzQRugzY7vMVcGs,5822,3156,5548,10613,842,576,683,1399,5.44,10.54,4.00,rc,res,1,0.00,1999.00,23.00,0,1,0,0
2,冬山鄉,宜蘭縣冬山鄉永興路二段９１巷１弄５２之１２號,145.54,NaN,特定農業區,1111206,土地3建物1車位0,三層,鋼筋混凝土造,1050627.00,176.94,4,2,5,有,無,11000000.00,62168.00,,RPUOMLPKKIHGFAG18DA,162.12,0.00,14.82,無,128.00,2022,12,ChIJNYDmW_DmZzQRX45dA0Kl6Gg,16533,12803,9392,5216,1907,1690,1215,768,0.00,8.38,3.00,rc,NaN,0,0.00,2016.00,6.00,0,1,0,0
3,三星鄉,宜蘭縣三星鄉大坑三路８８號,143.50,NaN,特定農業區,1111203,土地1建物1車位0,三層,鋼筋混凝土造,810730.00,159.27,4,2,3,有,無,6900000.00,43323.00,其他增建；,RPVOMLPKKIHGFAG28DA,159.27,0.00,0.00,無,129.00,2022,12,Ej1Oby4gODgsIERha2VuZyBSZCwgU2FueGluZyBUb3duc2...,21539,16472,14398,10164,2086,1796,1397,1392,0.00,0.00,3.00,rc,NaN,0,0.00,1992.00,30.00,0,1,0,0
4,三星鄉,宜蘭縣三星鄉上將路一段３３巷３８弄２５號,70.65,NaN,特定農業區,1111201,土地5建物1車位0,三層,鋼筋混凝土造,1110805.00,162.28,3,2,4,有,無,9150000.00,56384.00,,RPUOMLKLKIHGFAG87EA,146.73,0.00,15.55,無,135.00,2022,12,ElVOby4gMzgsIExhbmUgMzMsIFNlY3Rpb24gMSwgU2hhbm...,12162,8431,5021,4429,1193,976,500,605,0.00,9.58,3.00,rc,NaN,0,0.00,2022.00,0.00,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9372,員山鄉,宜蘭縣員山鄉榮光路２６４之１號,82.00,NaN,鄉村區,1070129,土地1建物1車位0,二層,鋼筋混凝土加強磚造,690131.00,85.79,3,1,2,有,無,4100000.00,47791.00,,RPPNMLNKKHNFFBG77CA,85.79,0.00,0.00,NaN,NaN,2018,1,ChIJxRAmRcfjZzQRqICYdl4csPc,12701,9833,10124,11566,1376,1144,802,1369,0.00,0.00,2.00,enf_brick,NaN,0,NaN,1980.00,38.00,0,1,0,0
9373,頭城鎮,宜蘭縣頭城鎮新興路231-30號,100.32,住,NaN,1070104,土地2建物1車位0,二層,鋼筋混凝土加強磚造,701224.00,133.76,4,2,2,有,無,7000000.00,52333.00,三樓加蓋面積64.5平方公尺,RPUNMLMKLHNFFBG38DA,133.76,0.00,0.00,NaN,NaN,2018,1,ChIJs_e1g1z3ZzQRMgte3FZRAuY,11639,15218,19493,25038,1083,1373,1441,1703,0.00,0.00,2.00,enf_brick,res,1,NaN,1981.00,37.00,0,1,0,0
9374,五結鄉,宜蘭縣五結鄉仁五路一段５１巷２號,158.32,農,NaN,1070123,土地3建物1車位0,三層,見其他登記事項,1040708.00,210.29,4,2,5,有,無,11400000.00,54211.00,,RPWNMLRLKHNFFAG88CA,194.65,0.00,15.64,NaN,NaN,2018,1,Ek1Oby4gMiwgTGFuZSA1MSwgU2VjdGlvbiAxLCBSZW53dS...,13466,11197,6090,2758,1066,1047,646,487,0.00,7.44,3.00,None,agr,1,NaN,2015.00,3.00,0,1,0,0
9375,冬山鄉,宜蘭縣冬山鄉寶和路１７６巷１２號,92.95,NaN,特定農業區,1070107,土地0建物1車位0,三層,見其他登記事項,1040709.00,172.31,4,2,4,有,無,8550000.00,49620.00,,RPRNMLOKKHNFFAG97CA,157.50,0.00,14.81,NaN,NaN,2018,1,ChIJcVqaZqnnZzQRR3UWu4A-tbQ,21862,15715,12304,6706,1927,1896,1420,844,0.00,8.59,3.00,None,NaN,0,NaN,2015.00,3.00,0,1,0,0
9376,五結鄉,宜蘭縣五結鄉新店路１４號,289.50,NaN,鄉村區,1070123,土地2建物1車位0,一層,磚造,671121.00,90.31,6,2,4,有,無,6600000.00,73082.00,,RPROMLNKKHNFFAG97CA,76.00,14.31,0.00,NaN,NaN,2018,1,ChIJMzJARkzvZzQRCwPO94giSUU,16602,15767,12007,6126,1461,1449,1102,769,15.85,0.00,1.00,brick,NaN,0,NaN,1978.00,40.00,0,1,0,0

In [22]:
# presale house from note
df['d_presale_2'] = df.apply(lambda row: 1 if ('預售屋、或土地及建物分件登記案件' in row['note']) else 0, axis = 1)
df['d_presale_2'].describe()

count   9377.00
mean       0.08
std        0.27
min        0.00
25%        0.00
50%        0.00
75%        0.00
max        1.00
Name: d_presale_2, dtype: float64

In [23]:
df['d_presale'].describe()

count   9377.00
mean       0.12
std        0.33
min        0.00
25%        0.00
50%        0.00
75%        0.00
max        1.00
Name: d_presale, dtype: float64

In [24]:
df['d_notreg'] = df.apply(lambda row: 1 if '未登記建物' in row['note'] else 0, axis = 1)
df['d_notreg'].describe()

count   9377.00
mean       0.06
std        0.24
min        0.00
25%        0.00
50%        0.00
75%        0.00
max        1.00
Name: d_notreg, dtype: float64

In [25]:
df['d_hotspring'] = df.apply(lambda row: 1 if '溫泉宅' in row['note'] else 0, axis = 1)
df['d_hotspring'].describe()

count   9377.00
mean       0.00
std        0.05
min        0.00
25%        0.00
50%        0.00
75%        0.00
max        1.00
Name: d_hotspring, dtype: float64

In [26]:
df['d_leak'] = df.apply(lambda row: 1 if '漏水' in row['note'] else 0, axis = 1)
df['d_leak'].describe()

count   9377.00
mean       0.00
std        0.06
min        0.00
25%        0.00
50%        0.00
75%        0.00
max        1.00
Name: d_leak, dtype: float64

In [27]:
df['d_reno'] = df.apply(lambda row: 1 if '含裝潢費' in row['note'] else 0, axis = 1)
df['d_leak'].describe()

count   9377.00
mean       0.00
std        0.06
min        0.00
25%        0.00
50%        0.00
75%        0.00
max        1.00
Name: d_leak, dtype: float64

In [28]:
df.columns

Index(['town', 'address', 'land_area', 'urb_zoning', 'nurb_zoning', 'date',
       'object_num', 'story', 'material', 'completion_date', 'building_area',
       'n_bed', 'n_hall', 'n_bath', 'old_d_comp', 'old_d_manager', 'price',
       'unitprice', 'note', 'serialnumber', 'main_area', 'aux_area',
       'balcony_area', 'old_d_elevator', 'trans_num', 'year', 'month',
       'place_id', 'dist_to四城', 'dist_to宜蘭', 'dist_to縣政中心', 'dist_to羅東',
       'dur_to四城', 'dur_to宜蘭', 'dur_to縣政中心', 'dur_to羅東', 'percent_aux',
       'percent_balcony', 'n_story', 'n_material', 'n_urb_zoning', 'd_urban',
       'd_elevator', 'completion_year', 'age', 'd_presale', 'd_comp',
       'd_manager', 'd_spec_rel', 'd_presale_2', 'd_notreg', 'd_hotspring',
       'd_leak', 'd_reno'],
      dtype='object')

In [29]:
df = df[['town', 'address', 'land_area', 'object_num', 'building_area',
       'n_bed', 'n_hall', 'n_bath', 'price', 'unitprice', 'main_area', 'aux_area',
       'balcony_area', 'trans_num', 'year', 'month', 'dist_to四城', 'dist_to宜蘭', 'dist_to縣政中心', 'dist_to羅東',
       'percent_aux', 'percent_balcony', 'n_story','n_material', 'n_urb_zoning', 'd_urban', 'd_elevator',
       'completion_year', 'age', 'd_presale', 'd_comp', 'd_manager', 'd_spec_rel',
       'd_presale_2', 'd_notreg', 'd_hotspring', 'd_leak', 'd_reno']]
df.columns

Index(['town', 'address', 'land_area', 'object_num', 'building_area', 'n_bed',
       'n_hall', 'n_bath', 'price', 'unitprice', 'main_area', 'aux_area',
       'balcony_area', 'trans_num', 'year', 'month', 'dist_to四城', 'dist_to宜蘭',
       'dist_to縣政中心', 'dist_to羅東', 'percent_aux', 'percent_balcony', 'n_story',
       'n_material', 'n_urb_zoning', 'd_urban', 'd_elevator',
       'completion_year', 'age', 'd_presale', 'd_comp', 'd_manager',
       'd_spec_rel', 'd_presale_2', 'd_notreg', 'd_hotspring', 'd_leak',
       'd_reno'],
      dtype='object')

In [30]:
df.describe()

,land_area,building_area,n_bed,n_hall,n_bath,price,unitprice,main_area,aux_area,balcony_area,trans_num,year,month,dist_to四城,dist_to宜蘭,dist_to縣政中心,dist_to羅東,percent_aux,percent_balcony,n_story,d_urban,d_elevator,completion_year,age,d_presale,d_comp,d_manager,d_spec_rel,d_presale_2,d_notreg,d_hotspring,d_leak,d_reno
count,9377.00,9377.00,9377.00,9377.00,9377.00,9377.00,9376.00,9377.00,9377.00,9377.00,1192.00,9377.00,9377.00,9377.00,9377.00,9377.00,9377.00,9377.00,9377.00,9375.00,9377.00,6023.00,9111.00,9111.00,9377.00,9377.00,9377.00,9377.00,9377.00,9377.00,9377.00,9377.00,9377.00
mean,127.10,166.70,3.69,1.92,3.32,8943302.45,55393.91,154.37,2.30,9.44,302.18,2020.13,6.77,12944.52,10439.76,9313.55,9176.93,1.25,4.90,2.76,0.48,0.08,2001.81,18.47,0.12,0.96,0.02,0.04,0.08,0.06,0.00,0.00,0.00
std,269.05,64.86,1.42,0.73,1.40,6198093.05,44422.14,58.69,6.74,9.23,167.03,1.33,3.42,7026.73,6542.99,5074.83,5882.32,3.73,4.49,0.71,0.50,0.28,18.76,18.60,0.33,0.18,0.15,0.20,0.27,0.24,0.05,0.06,0.05
min,4.34,1.86,0.00,0.00,0.00,50000.00,1121.00,0.00,0.00,0.00,1.00,2018.00,1.00,118.00,156.00,90.00,177.00,0.00,0.00,1.00,0.00,0.00,1925.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,84.86,122.27,3.00,2.00,2.00,5800000.00,40923.25,118.56,0.00,0.00,166.00,2019.00,4.00,6559.00,5003.00,5747.00,4712.00,0.00,0.00,2.00,0.00,0.00,1981.00,1.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,101.99,168.19,4.00,2.00,3.00,8080000.00,49752.50,154.03,0.00,10.16,298.00,2020.00,7.00,13105.00,10135.00,8211.00,8675.00,0.00,5.45,3.00,0.00,0.00,2011.00,9.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
75%,124.64,197.99,4.00,2.00,4.00,10980000.00,61636.25,180.72,0.00,15.26,433.00,2021.00,10.00,18237.00,14144.00,12304.00,12443.00,0.00,8.48,3.00,1.00,0.00,2019.00,38.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
max,17374.66,1066.49,18.00,8.00,18.00,270000000.00,2043165.00,1040.79,119.81,131.11,673.00,2022.00,12.00,62205.00,57255.00,61531.00,67076.00,60.39,29.39,5.00,1.00,1.00,2022.00,96.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00

In [31]:
np.round(df.describe(), 2).T

,count,mean,std,min,25%,50%,75%,max
land_area,9377.00,127.10,269.05,4.34,84.86,101.99,124.64,17374.66
building_area,9377.00,166.70,64.86,1.86,122.27,168.19,197.99,1066.49
n_bed,9377.00,3.69,1.42,0.00,3.00,4.00,4.00,18.00
n_hall,9377.00,1.92,0.73,0.00,2.00,2.00,2.00,8.00
n_bath,9377.00,3.32,1.40,0.00,2.00,3.00,4.00,18.00
price,9377.00,8943302.45,6198093.05,50000.00,5800000.00,8080000.00,10980000.00,270000000.00
unitprice,9376.00,55393.91,44422.14,1121.00,40923.25,49752.50,61636.25,2043165.00
main_area,9377.00,154.37,58.69,0.00,118.56,154.03,180.72,1040.79
aux_area,9377.00,2.30,6.74,0.00,0.00,0.00,0.00,119.81
balcony_area,9377.00,9.44,9.23,0.00,0.00,10.16,15.26,131.11
trans_num,1192.00,302.18,167.03,1.00,166.00,298.00,433.00,673.00
year,9377.00,2020.13,1.33,2018.00,2019.00,2020.00,2021.00,2022.00
month,9377.00,6.77,3.42,1.00,4.00,7.00,10.00,12.00
dist_to四城,9377.00,12944.52,7026.73,118.00,6559.00,13105.00,18237.00,62205.00
dist_to宜蘭,9377.00,10439.76,6542.99,156.00,5003.00,10135.00,14144.00,57255.00
dist_to縣政中心,9377.00,9313.55,5074.83,90.00,5747.00,8211.00,12304.00,61531.00
dist_to羅東,9377.00,9176.93,5882.32,177.00,4712.00,8675.00,12443.00,67076.00
percent_aux,9377.00,1.25,3.73,0.00,0.00,0.00,0.00,60.39
percent_balcony,9377.00,4.90,4.49,0.00,0.00,5.45,8.48,29.39
n_story,9375.00,2.76,0.71,1.00,2.00,3.00,3.00,5.00
d_urban,9377.00,0.48,0.50,0.00,0.00,0.00,1.00,1.00
d_elevator,6023.00,0.08,0.28,0.00,0.00,0.00,0.00,1.00
completion_year,9111.00,2001.81,18.76,1925.00,1981.00,2011.00,2019.00,2022.00
age,9111.00,18.47,18.60,0.00,1.00,9.00,38.00,96.00
d_presale,9377.00,0.12,0.33,0.00,0.00,0.00,0.00,1.00
d_comp,9377.00,0.96,0.18,0.00,1.00,1.00,1.00,1.00
d_manager,9377.00,0.02,0.15,0.00,0.00,0.00,0.00,1.00
d_spec_rel,9377.00,0.04,0.20,0.00,0.00,0.00,0.00,1.00
d_presale_2,9377.00,0.08,0.27,0.00,0.00,0.00,0.00,1.00
d_notreg,9377.00,0.06,0.24,0.00,0.00,0.00,0.00,1.00
d_hotspring,9377.00,0.00,0.05,0.00,0.00,0.00,0.00,1.00
d_leak,9377.00,0.00,0.06,0.00,0.00,0.00,0.00,1.00
d_reno,9377.00,0.00,0.05,0.00,0.00,0.00,0.00,1.00

In [32]:
np.round(df.describe(), 2).T[['count','mean', 'std', 'min', 'max']]

                  count       mean        std      min          max
land_area       9377.00     127.10     269.05     4.34     17374.66
building_area   9377.00     166.70      64.86     1.86      1066.49
n_bed           9377.00       3.69       1.42     0.00        18.00
n_hall          9377.00       1.92       0.73     0.00         8.00
n_bath          9377.00       3.32       1.40     0.00        18.00
price           9377.00 8943302.45 6198093.05 50000.00 270000000.00
unitprice       9376.00   55393.91   44422.14  1121.00   2043165.00
main_area       9377.00     154.37      58.69     0.00      1040.79
aux_area        9377.00       2.30       6.74     0.00       119.81
balcony_area    9377.00       9.44       9.23     0.00       131.11
trans_num       1192.00     302.18     167.03     1.00       673.00
year            9377.00    2020.13       1.33  2018.00      2022.00
month           9377.00       6.77       3.42     1.00        12.00
dist_to四城       9377.00   12944.52    7026.73   118.00     62205.00
dist_to宜蘭       9377.00   10439.76    6542.99   156.00     57255.00
dist_to縣政中心     9377.00    9313.55    5074.83    90.00     61531.00
dist_to羅東       9377.00    9176.93    5882.32   177.00     67076.00
percent_aux     9377.00       1.25       3.73     0.00        60.39
percent_balcony 9377.00       4.90       4.49     0.00        29.39
n_story         9375.00       2.76       0.71     1.00         5.00
d_urban         9377.00       0.48       0.50     0.00         1.00
d_elevator      6023.00       0.08       0.28     0.00         1.00
completion_year 9111.00    2001.81      18.76  1925.00      2022.00
age             9111.00      18.47      18.60     0.00        96.00
d_presale       9377.00       0.12       0.33     0.00         1.00
d_comp          9377.00       0.96       0.18     0.00         1.00
d_manager       9377.00       0.02       0.15     0.00         1.00
d_spec_rel      9377.00       0.04       0.20     0.00         1.00
d_presale_2     9377.00       0.08       0.27     0.00         1.00
d_notreg        9377.00       0.06       0.24     0.00         1.00
d_hotspring     9377.00       0.00       0.05     0.00         1.00
d_leak          9377.00       0.00       0.06     0.00         1.00
d_reno          9377.00       0.00       0.05     0.00         1.00

## Find closest station

In [33]:
df.columns

Index(['town', 'address', 'land_area', 'object_num', 'building_area', 'n_bed',
       'n_hall', 'n_bath', 'price', 'unitprice', 'main_area', 'aux_area',
       'balcony_area', 'trans_num', 'year', 'month', 'dist_to四城', 'dist_to宜蘭',
       'dist_to縣政中心', 'dist_to羅東', 'percent_aux', 'percent_balcony', 'n_story',
       'n_material', 'n_urb_zoning', 'd_urban', 'd_elevator',
       'completion_year', 'age', 'd_presale', 'd_comp', 'd_manager',
       'd_spec_rel', 'd_presale_2', 'd_notreg', 'd_hotspring', 'd_leak',
       'd_reno'],
      dtype='object')

In [34]:
def find_closest_station(row):
    closest_station = ''
    min_distance = 999999999
    for s in ('四城', '宜蘭', '縣政中心', '羅東'):
        if row[f'dist_to{s}'] < min_distance:
            closest_station = s
            min_distance = row[f'dist_to{s}']
    return closest_station

In [35]:
df['closest_station'] = df.apply(lambda row: find_closest_station(row), axis = 1)
df['min_dist'] = df[['dist_to四城', 'dist_to宜蘭', 'dist_to縣政中心', 'dist_to羅東']].min(axis=1)

/var/folders/6b/l8cgp_y91pz6_17n81klfkw80000gn/T/ipykernel_97817/393953869.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['closest_station'] = df.apply(lambda row: find_closest_station(row), axis = 1)
/var/folders/6b/l8cgp_y91pz6_17n81klfkw80000gn/T/ipykernel_97817/393953869.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['min_dist'] = df[['dist_to四城', 'dist_to宜蘭', 'dist_to縣政中心', 'dist_to羅東']].min(axis=1)

In [36]:
df.head()

,town,address,land_area,object_num,building_area,n_bed,n_hall,n_bath,price,unitprice,main_area,aux_area,balcony_area,trans_num,year,month,dist_to四城,dist_to宜蘭,dist_to縣政中心,dist_to羅東,percent_aux,percent_balcony,n_story,n_material,n_urb_zoning,d_urban,d_elevator,completion_year,age,d_presale,d_comp,d_manager,d_spec_rel,d_presale_2,d_notreg,d_hotspring,d_leak,d_reno,closest_station,min_dist
0,五結鄉,宜蘭縣五結鄉孝威路３３３巷９號,107.93,土地3建物1車位0,182.43,4,3,3,9000000.00,49334.00,169.09,0.00,13.34,NaN,2022,12,14608,12338,8568,5998,0.00,7.31,3.00,rc,NaN,0,0.00,2016.00,6.00,0,1,0,0,0,0,0,0,0,羅東,5998
1,宜蘭市,宜蘭縣宜蘭市女中路三段５８１號,87.62,土地1建物1車位0,257.08,5,3,4,15800000.00,61459.00,216.00,13.99,27.09,NaN,2022,12,5822,3156,5548,10613,5.44,10.54,4.00,rc,res,1,0.00,1999.00,23.00,0,1,0,0,0,0,0,0,0,宜蘭,3156
2,冬山鄉,宜蘭縣冬山鄉永興路二段９１巷１弄５２之１２號,145.54,土地3建物1車位0,176.94,4,2,5,11000000.00,62168.00,162.12,0.00,14.82,128.00,2022,12,16533,12803,9392,5216,0.00,8.38,3.00,rc,NaN,0,0.00,2016.00,6.00,0,1,0,0,0,0,0,0,0,羅東,5216
3,三星鄉,宜蘭縣三星鄉大坑三路８８號,143.50,土地1建物1車位0,159.27,4,2,3,6900000.00,43323.00,159.27,0.00,0.00,129.00,2022,12,21539,16472,14398,10164,0.00,0.00,3.00,rc,NaN,0,0.00,1992.00,30.00,0,1,0,0,0,0,0,0,0,羅東,10164
4,三星鄉,宜蘭縣三星鄉上將路一段３３巷３８弄２５號,70.65,土地5建物1車位0,162.28,3,2,4,9150000.00,56384.00,146.73,0.00,15.55,135.00,2022,12,12162,8431,5021,4429,0.00,9.58,3.00,rc,NaN,0,0.00,2022.00,0.00,0,1,0,0,0,0,0,0,0,羅東,4429

In [37]:
df.to_csv('11Input/02DataProcessed/cleaned.csv', index=False)